# Where's the stuff?
source              : .
destination         : data/_site
data_dir            : data/quotes

collections_dir     : data/
layouts_dir         : ./data/_layouts
includes_dir        : data/_includes
sass_dir            : data/css

safe: true

# General Site settings
title: Kliquote
email: 
description: >-
  Kliemann'sche Zitate. Natürlich auch mit Zitaten der Gang.
keywords: fynn kliemann,kliemann,zitate,kliemannsland,youtube
baseurl: /kliquote/
url: https://error418.github.io
github_username: error418/kliquote
github: https://github.com/error418/kliquote

# Build settings
sass:
  style: compressed
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-coffeescript

include:
  - data/
  - index.html

# Excludes
exclude:
  - node_modules/
  - bin/
  - .bundle/
  - routes/
  - dist/
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - app.js
  - package.json
  - package-lock.json
  - readme.md
