# Where's the stuff?
source              : ./data
destination         : data/_site
collections_dir     : .
plugins_dir         : _plugins
layouts_dir         : _layouts
data_dir            : quotes
includes_dir        : _includes

safe: true

# General Site settings
title: Kliquote
email: 
description: >-
  Kliemannsche Zitate
baseurl: "/kliquote/" # the subpath of your site, e.g. /blog
url: "https://error418.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: error418/kliquote
github: https://github.com/error418/kliquote

# Build settings
sass:
  style: compressed
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-coffeescript

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - activity-diagram.puml
  - .vendor
